### ISSUE TITLE
`isValidInstance`

### ISSUE THREAD

**Issue by doowb** [node-base/base-plugins#2]
@jonschlinkert should [this](https://github.com/node-base/base-plugins/blob/master/index.js#L120-L122) be returning `true` instead of `false` if the instance is a Collection or View? Or maybe removed completely?

**Comment by jonschlinkert** [comment]
yes, you're right. did we unpublished this version earlier?

**Comment by doowb** [comment]
Yes, this was the issue in templates. There's another issue in `base-data`, but I'm not sure what it is.

**Comment by doowb** [comment]
Closing. I just saw the latest changes and verified in `assemble` tests.

**Comment by jonschlinkert** [comment]
k thx
